services:

  myapp:
    build: .
    container_name: myapp
    restart: always
    ports:
      - 8080:80
    volumes:
      - "C:/Users/mathe/Documents/docker/html:/usr/share/nginx/html"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : fullcycle
  
    ports:
      - 3307:3306
    volumes:
      - "C:/Users/mathe/Documents/docker/mysql:/var/lib/mysql"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart : always
    ports:
      - 5672:5672
      - 15672:15672